/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  projectsSidebar: [
    'intro',
    {
      type: 'category',
      label: '🚀 Projects',
      link: {
        type: 'doc',
        id: 'projects/index',
      },
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'projects',
        },
      ],
    },
    'about',
  ],
};

module.exports = sidebars;
